// Copyright 2026 dmmdea and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newClipCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "clip",
		Short:       "one media pool clip: properties, metadata, markers, flags, marks, proxies, AI passes, transcription",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newClipAddMarkerCmd(flags))
	cmd.AddCommand(newClipAiCmd(flags))
	cmd.AddCommand(newClipColorCmd(flags))
	cmd.AddCommand(newClipDeleteMarkerCmd(flags))
	cmd.AddCommand(newClipFlagCmd(flags))
	cmd.AddCommand(newClipInfoCmd(flags))
	cmd.AddCommand(newClipMarkCmd(flags))
	cmd.AddCommand(newClipMarkersCmd(flags))
	cmd.AddCommand(newClipMonitorGrowingCmd(flags))
	cmd.AddCommand(newClipProxyCmd(flags))
	cmd.AddCommand(newClipRenameCmd(flags))
	cmd.AddCommand(newClipReplaceCmd(flags))
	cmd.AddCommand(newClipSetAudioMappingCmd(flags))
	cmd.AddCommand(newClipSetMetadataCmd(flags))
	cmd.AddCommand(newClipSetPropertyCmd(flags))
	cmd.AddCommand(newClipTranscriptionCmd(flags))
	return cmd
}
