// Copyright 2026 dmmdea and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newColorCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "color",
		Short:       "grade versions, LUT/CDL/DRX, node graph, color groups, gallery",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newColorApplyCdlCmd(flags))
	cmd.AddCommand(newColorApplyDrxCmd(flags))
	cmd.AddCommand(newColorApplyLutCmd(flags))
	cmd.AddCommand(newColorCopyGradeCmd(flags))
	cmd.AddCommand(newColorExportLutCmd(flags))
	cmd.AddCommand(newColorGalleryCmd(flags))
	cmd.AddCommand(newColorGalleryAlbumCmd(flags))
	cmd.AddCommand(newColorGroupCmd(flags))
	cmd.AddCommand(newColorGroupsCmd(flags))
	cmd.AddCommand(newColorInfoCmd(flags))
	cmd.AddCommand(newColorRefreshLutsCmd(flags))
	cmd.AddCommand(newColorSetNodeCmd(flags))
	cmd.AddCommand(newColorTimelineGraphCmd(flags))
	cmd.AddCommand(newColorVersionCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelColorAuditCmd(flags))
	return cmd
}
