// Copyright 2026 dmmdea and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newFusionCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "fusion",
		Short:       "Fusion tool scripting on an item's comp (Lock/Undo wrapped) and the Text+ shortcut",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newFusionKeyframesCmd(flags))
	cmd.AddCommand(newFusionSetCmd(flags))
	cmd.AddCommand(newFusionSetTitleCmd(flags))
	cmd.AddCommand(newFusionToolCmd(flags))
	cmd.AddCommand(newFusionToolsCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelFusionTitlesCmd(flags))
	return cmd
}
