// Copyright 2026 dmmdea and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newFusionToolsCmd(flags *rootFlags) *cobra.Command {
	var flagItem string
	var flagComp int
	var flagRegid string
	var flagReadInputs string
	var flagAllInputs bool
	var flagTimeline string

	cmd := &cobra.Command{
		Use:         "tools",
		Short:       "tools in an item's Fusion comp (+ input values with --inputs / --all-inputs)",
		Example:     "  davinci-resolve-pp-cli fusion tools",
		Annotations: map[string]string{"pp:endpoint": "fusion.tools", "pp:method": "GET", "pp:path": "/v1/fusion-tools", "mcp:read-only": "true", "pp:happy-args": "--item=V1:1;--timeline=_ref_cli_tl;--regid=TextPlus"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("read-inputs") {
				var parsedReadInputs any
				if err := json.Unmarshal([]byte(flagReadInputs), &parsedReadInputs); err != nil {
					return fmt.Errorf("--read-inputs must be valid JSON: %w", err)
				}
			}
			path := "/v1/fusion-tools"
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			if flagItem != "" {
				params["item"] = formatCLIParamValue(flagItem)
			}
			if flagComp != 0 {
				params["comp"] = formatCLIParamValue(flagComp)
			}
			if flagRegid != "" {
				params["regid"] = formatCLIParamValue(flagRegid)
			}
			if flagReadInputs != "" {
				params["read-inputs"] = formatCLIParamValue(flagReadInputs)
			}
			if flagAllInputs != false {
				params["all-inputs"] = formatCLIParamValue(flagAllInputs)
			}
			if flagTimeline != "" {
				params["timeline"] = formatCLIParamValue(flagTimeline)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "auto", "fusion", false, path, params, nil, "", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := data
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(outputData, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered, nil)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				wrapped, wrapErr = wrapPlatformStructuredOutput(wrapped, flags, "results", true)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, nil)
		},
	}
	cmd.Flags().StringVar(&flagItem, "item", "", "timeline item: 'V1:3', unique id, or name")
	cmd.Flags().IntVar(&flagComp, "comp", 0, "Fusion comp index on the item (default 1)")
	cmd.Flags().StringVar(&flagRegid, "regid", "", "filter by RegID, e.g. TextPlus")
	cmd.Flags().StringVar(&flagReadInputs, "read-inputs", "", "input ids to read on each tool (comma-free single value or a JSON array string)")
	cmd.Flags().BoolVar(&flagAllInputs, "all-inputs", false, "all inputs")
	cmd.Flags().StringVar(&flagTimeline, "timeline", "", "named timeline (never switches the GUI); default: current")

	return cmd
}
