// Copyright 2026 dmmdea and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newItemCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "item",
		Short:       "timeline items: properties, speed, fades, transitions, multicam, Fusion comps",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newItemAddTransitionCmd(flags))
	cmd.AddCommand(newItemDeleteCmd(flags))
	cmd.AddCommand(newItemFusionCompCmd(flags))
	cmd.AddCommand(newItemFusionCompsCmd(flags))
	cmd.AddCommand(newItemInfoCmd(flags))
	cmd.AddCommand(newItemLinkCmd(flags))
	cmd.AddCommand(newItemListCmd(flags))
	cmd.AddCommand(newItemMulticamCmd(flags))
	cmd.AddCommand(newItemSetCmd(flags))
	cmd.AddCommand(newItemSetPropertiesCmd(flags))
	return cmd
}
