// Copyright 2026 dmmdea and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPoolCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "pool",
		Short:       "media pool bins and clip lifecycle",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPoolBinCmd(flags))
	cmd.AddCommand(newPoolBinsCmd(flags))
	cmd.AddCommand(newPoolClipsCmd(flags))
	cmd.AddCommand(newPoolDeleteClipsCmd(flags))
	cmd.AddCommand(newPoolImportCmd(flags))
	cmd.AddCommand(newPoolImportPathsCmd(flags))
	cmd.AddCommand(newPoolMoveClipsCmd(flags))
	cmd.AddCommand(newPoolRelinkClipsCmd(flags))
	cmd.AddCommand(newPoolSelectClipCmd(flags))
	cmd.AddCommand(newPoolSelectionCmd(flags))
	cmd.AddCommand(newPoolStereoClipCmd(flags))
	cmd.AddCommand(newPoolSyncAudioCmd(flags))
	return cmd
}
