// Copyright 2026 dmmdea and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newRenderCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "render",
		Short:       "render formats, settings, presets, job queue, quick export, verify-by-file",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newRenderAddJobCmd(flags))
	cmd.AddCommand(newRenderDeleteJobCmd(flags))
	cmd.AddCommand(newRenderFormatsCmd(flags))
	cmd.AddCommand(newRenderJobStatusCmd(flags))
	cmd.AddCommand(newRenderJobsCmd(flags))
	cmd.AddCommand(newRenderPresetCmd(flags))
	cmd.AddCommand(newRenderPresetsCmd(flags))
	cmd.AddCommand(newRenderQueueCmd(flags))
	cmd.AddCommand(newRenderQuickExportCmd(flags))
	cmd.AddCommand(newRenderQuickExportPresetsCmd(flags))
	cmd.AddCommand(newRenderRenderCmd(flags))
	cmd.AddCommand(newRenderSetFormatCmd(flags))
	cmd.AddCommand(newRenderSetModeCmd(flags))
	cmd.AddCommand(newRenderSetSettingsCmd(flags))
	cmd.AddCommand(newRenderSmokeCmd(flags))
	cmd.AddCommand(newRenderStartCmd(flags))
	cmd.AddCommand(newRenderStopCmd(flags))
	cmd.AddCommand(newRenderVerifyCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelRenderHistoryCmd(flags))
	return cmd
}
