// Copyright 2026 dmmdea and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newStorageCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "storage",
		Short:       "media storage browsing/import and the 21.1 clone tool",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newStorageBrowseCmd(flags))
	cmd.AddCommand(newStorageCloneMediaCmd(flags))
	cmd.AddCommand(newStorageCloneStatusCmd(flags))
	cmd.AddCommand(newStorageImportCmd(flags))
	cmd.AddCommand(newStorageVolumesCmd(flags))
	return cmd
}
