// Copyright 2026 dmmdea and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSystemCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "system",
		Short:       "Resolve app state: status, page, system presets, keyframe mode, background tasks, DCTL, quit",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSystemApplyCmd(flags))
	cmd.AddCommand(newSystemDisableBackgroundTasksCmd(flags))
	cmd.AddCommand(newSystemEncryptDctlCmd(flags))
	cmd.AddCommand(newSystemExportFrameCmd(flags))
	cmd.AddCommand(newSystemKeyframeModeCmd(flags))
	cmd.AddCommand(newSystemListCmd(flags))
	cmd.AddCommand(newSystemPageCmd(flags))
	cmd.AddCommand(newSystemQuitCmd(flags))
	cmd.AddCommand(newSystemSetKeyframeModeCmd(flags))
	cmd.AddCommand(newSystemStatusCmd(flags))
	cmd.AddCommand(newSystemThumbnailCmd(flags))
	cmd.AddCommand(newSystemValidateDctlCmd(flags))
	return cmd
}
