// Copyright 2026 dmmdea and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTimelineCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "timeline",
		Short:       "timelines, tracks, markers, timecode, settings, generators, timeline AI, import/export, build",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTimelineAddMarkerCmd(flags))
	cmd.AddCommand(newTimelineAddTrackCmd(flags))
	cmd.AddCommand(newTimelineAiCmd(flags))
	cmd.AddCommand(newTimelineAppendCmd(flags))
	cmd.AddCommand(newTimelineBuildCmd(flags))
	cmd.AddCommand(newTimelineClipsCmd(flags))
	cmd.AddCommand(newTimelineCompoundClipCmd(flags))
	cmd.AddCommand(newTimelineCreateCmd(flags))
	cmd.AddCommand(newTimelineCreateFromClipsCmd(flags))
	cmd.AddCommand(newTimelineDeleteCmd(flags))
	cmd.AddCommand(newTimelineDeleteMarkerCmd(flags))
	cmd.AddCommand(newTimelineDeleteTrackCmd(flags))
	cmd.AddCommand(newTimelineDuplicateCmd(flags))
	cmd.AddCommand(newTimelineExportCmd(flags))
	cmd.AddCommand(newTimelineExportSpecCmd(flags))
	cmd.AddCommand(newTimelineFusionClipCmd(flags))
	cmd.AddCommand(newTimelineGrabStillCmd(flags))
	cmd.AddCommand(newTimelineImportCmd(flags))
	cmd.AddCommand(newTimelineInfoCmd(flags))
	cmd.AddCommand(newTimelineInsertGeneratorCmd(flags))
	cmd.AddCommand(newTimelineListCmd(flags))
	cmd.AddCommand(newTimelineMarkCmd(flags))
	cmd.AddCommand(newTimelineMarkersCmd(flags))
	cmd.AddCommand(newTimelineNormalizeModesCmd(flags))
	cmd.AddCommand(newTimelineRenameCmd(flags))
	cmd.AddCommand(newTimelineSetBlankingCmd(flags))
	cmd.AddCommand(newTimelineSetSettingsCmd(flags))
	cmd.AddCommand(newTimelineSetTimecodeCmd(flags))
	cmd.AddCommand(newTimelineSetTrackCmd(flags))
	cmd.AddCommand(newTimelineSettingsCmd(flags))
	cmd.AddCommand(newTimelineSwitchCmd(flags))
	cmd.AddCommand(newTimelineTimecodeCmd(flags))
	cmd.AddCommand(newTimelineTracksCmd(flags))
	addNovelCommandIfAbsent(cmd, newNovelTimelineLogCmd(flags))
	return cmd
}
