// Copyright 2026 dmmdea and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package mcp — code-orchestration thin surface.
//
// Three tools cover the entire API: <api>_search to discover endpoints,
// <api>_get to inspect one GET endpoint, and <api>_execute to invoke one.
// This collapses a large API (50+ endpoints)
// to ~1K tokens of tool definitions while preserving full coverage — the
// agent writes the composition logic in its own sandbox.
//
// Pattern source: Anthropic 2026-04-22 "Building agents that reach
// production systems with MCP" — Cloudflare's MCP server covers ~2,500
// endpoints in roughly 1K tokens via the same search, get, and execute shape.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	neturl "net/url"
	"sort"
	"strings"

	"github.com/dmmdea/davinci-resolve-cli/cli/internal/cli"
	"github.com/dmmdea/davinci-resolve-cli/cli/internal/mcp/bound"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterCodeOrchestrationTools registers the agent-facing tools that cover
// the whole API surface. Called from RegisterTools in place of the per-endpoint
// registrations when MCP.Orchestration is "code".
func RegisterCodeOrchestrationTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("davinci-resolve_search",
			mcplib.WithDescription("Search the davinci-resolve API for endpoints matching a natural-language query. Returns a ranked list of {endpoint_id, method, path, summary} entries. Call this first to find the endpoint to execute."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Natural-language description of what you want to do.")),
			mcplib.WithNumber("limit", mcplib.Description("Max endpoints to return (default 10, max 100).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(false),
		),
		handleCodeOrchSearch,
	)

	s.AddTool(
		mcplib.NewTool("davinci-resolve_get",
			mcplib.WithDescription("Get metadata for one GET endpoint by its endpoint_id (from davinci-resolve_search). This registry-only lookup never calls the API."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("GET endpoint identifier returned by davinci-resolve_search (e.g., \"users.list\").")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(false),
		),
		handleCodeOrchGet,
	)

	s.AddTool(
		mcplib.NewTool("davinci-resolve_execute",
			mcplib.WithDescription("Execute one davinci-resolve API endpoint by its endpoint_id (from davinci-resolve_search). Params are passed as a JSON object; path placeholders and query strings are resolved automatically."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("Endpoint identifier returned by davinci-resolve_search (e.g., \"users.list\").")),
			mcplib.WithObject("params", mcplib.Description("Parameters for the endpoint. Path placeholders match by name; remaining entries become query string on GET/DELETE or JSON body on POST/PUT/PATCH.")),
		),
		handleCodeOrchExecute,
	)
}

// codeOrchEndpoint captures the small slice of endpoint metadata the
// registry tools need at runtime. `keywords` is a precomputed
// lowercase stream of description + path tokens used for naive ranking;
// anything more sophisticated belongs on the agent side.
type codeOrchEndpoint struct {
	ID         string
	Method     string
	Path       string
	Tier       string
	Summary    string
	Positional []string
	// TemplateParams carries public-to-wire bindings for promoted global path
	// placeholders. These resolve through Config.TemplateVars just like the
	// per-endpoint MCP tool inputs do.
	TemplateParams []codeOrchParamBinding
	// QueryParams carries public-to-wire bindings for spec-declared in:query
	// parameters. Write methods (POST/PUT/PATCH) route these to the query
	// string instead of dumping them into the JSON body. Derived from the
	// same mcpParamBindings location data the per-endpoint tools use.
	QueryParams []codeOrchParamBinding
	// Keep declared headers out of query/body routing so execution sends them
	// through the request-header map.
	HeaderParams []codeOrchParamBinding
	// HeaderOverrides carries per-endpoint request headers (e.g. an
	// Accept override for binary-only response endpoints). Without
	// threading these through, the code-orchestration execute path
	// sends the client's default Accept and binary endpoints 406.
	HeaderOverrides map[string]string
	// BodyIsArray marks endpoints whose request body schema root is a
	// bare top-level JSON array. The execute path then sends a top-level
	// array (the agent supplies it as params["body"]) instead of the
	// params object; a strict-mapping API rejects an object at the body
	// root with HTTP 422 "Invalid json".
	BodyIsArray bool
	Mutating    bool
	keywords    []string
}

type codeOrchParamBinding struct {
	PublicName string
	WireName   string
	Default    string
}

// codeOrchEndpoints is the generator-populated registry covering every
// endpoint declared in the spec. Kept flat on purpose — the agent queries
// via <api>_search, so hierarchy shows up as dotted IDs, not nested maps.
var codeOrchEndpoints = []codeOrchEndpoint{
	{
		ID:             "audio.insert",
		Method:         "POST",
		Path:           "/v1/insert-audio",
		Summary:        "InsertAudioToCurrentTrackAtPlayhead (Fairlight page)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("audio", "insert", "InsertAudioToCurrentTrackAtPlayhead (Fairlight page)", "/v1/insert-audio"),
	},
	{
		ID:             "audio.tts",
		Method:         "POST",
		Path:           "/v1/tts",
		Summary:        "GenerateSpeech text-to-speech (needs the AI Speech Generator Extras pack; returns an error without it)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("audio", "tts", "GenerateSpeech text-to-speech (needs the AI Speech Generator Extras pack; returns an error without it)", "/v1/tts"),
	},
	{
		ID:             "clip.add-marker",
		Method:         "POST",
		Path:           "/v1/add-clip-marker",
		Summary:        "add a marker to a media pool clip",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("clip", "add-marker", "add a marker to a media pool clip", "/v1/add-clip-marker"),
	},
	{
		ID:             "clip.ai",
		Method:         "POST",
		Path:           "/v1/clip-ai",
		Summary:        "AI pass on a clip or bin",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("clip", "ai", "AI pass on a clip or bin", "/v1/clip-ai"),
	},
	{
		ID:             "clip.color",
		Method:         "POST",
		Path:           "/v1/clip-color",
		Summary:        "set the clip color, or 'clear'",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("clip", "color", "set the clip color, or 'clear'", "/v1/clip-color"),
	},
	{
		ID:             "clip.delete-marker",
		Method:         "POST",
		Path:           "/v1/delete-clip-marker",
		Summary:        "delete clip markers by --frame, --custom-data or --color/All",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("clip", "delete-marker", "delete clip markers by --frame, --custom-data or --color/All", "/v1/delete-clip-marker"),
	},
	{
		ID:             "clip.flag",
		Method:         "POST",
		Path:           "/v1/clip-flag",
		Summary:        "add a flag (--add COLOR) or clear flags (--remove COLOR|All)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("clip", "flag", "add a flag (--add COLOR) or clear flags (--remove COLOR|All)", "/v1/clip-flag"),
	},
	{
		ID:             "clip.info",
		Method:         "GET",
		Path:           "/v1/clip-info",
		Summary:        "every clip property + metadata, flags, color, marks, markers, audio mapping",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "clip", WireName: "clip"}, {PublicName: "bin", WireName: "bin"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("clip", "info", "every clip property + metadata, flags, color, marks, markers, audio mapping", "/v1/clip-info"),
	},
	{
		ID:             "clip.mark",
		Method:         "POST",
		Path:           "/v1/clip-mark",
		Summary:        "set (--mark-in/--mark-out) or --clear clip mark in/out",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("clip", "mark", "set (--mark-in/--mark-out) or --clear clip mark in/out", "/v1/clip-mark"),
	},
	{
		ID:             "clip.markers",
		Method:         "GET",
		Path:           "/v1/clip-markers",
		Summary:        "markers on a media pool clip (customData decoded)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "clip", WireName: "clip"}, {PublicName: "bin", WireName: "bin"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("clip", "markers", "markers on a media pool clip (customData decoded)", "/v1/clip-markers"),
	},
	{
		ID:             "clip.monitor-growing",
		Method:         "POST",
		Path:           "/v1/monitor-growing",
		Summary:        "MonitorGrowingFile on a clip",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("clip", "monitor-growing", "MonitorGrowingFile on a clip", "/v1/monitor-growing"),
	},
	{
		ID:             "clip.proxy",
		Method:         "POST",
		Path:           "/v1/proxy",
		Summary:        "link a proxy (--link PATH), full-res media (--full-res PATH) or --unlink",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("clip", "proxy", "link a proxy (--link PATH), full-res media (--full-res PATH) or --unlink", "/v1/proxy"),
	},
	{
		ID:             "clip.rename",
		Method:         "POST",
		Path:           "/v1/rename-clip",
		Summary:        "rename a media pool clip",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("clip", "rename", "rename a media pool clip", "/v1/rename-clip"),
	},
	{
		ID:             "clip.replace",
		Method:         "POST",
		Path:           "/v1/replace-clip",
		Summary:        "ReplaceClip / --preserve-subclip",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("clip", "replace", "ReplaceClip / --preserve-subclip", "/v1/replace-clip"),
	},
	{
		ID:             "clip.set-audio-mapping",
		Method:         "POST",
		Path:           "/v1/set-audio-mapping",
		Summary:        "21-1 SetAudioMapping from JSON (track_mapping)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("clip", "set-audio-mapping", "21-1 SetAudioMapping from JSON (track_mapping)", "/v1/set-audio-mapping"),
	},
	{
		ID:             "clip.set-metadata",
		Method:         "POST",
		Path:           "/v1/set-clip-metadata",
		Summary:        "SetMetadata / --third-party SetThirdPartyMetadata from JSON",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("clip", "set-metadata", "SetMetadata / --third-party SetThirdPartyMetadata from JSON", "/v1/set-clip-metadata"),
	},
	{
		ID:             "clip.set-property",
		Method:         "POST",
		Path:           "/v1/set-clip-property",
		Summary:        "SetClipProperty (FPS, Alpha mode, Super Scale, ) with readback",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("clip", "set-property", "SetClipProperty (FPS, Alpha mode, Super Scale, ) with readback", "/v1/set-clip-property"),
	},
	{
		ID:             "clip.transcription",
		Method:         "GET",
		Path:           "/v1/transcription",
		Summary:        "21-1 transcript readback (segments, speakers, word timing)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "clip", WireName: "clip"}, {PublicName: "nested", WireName: "nested"}, {PublicName: "bin", WireName: "bin"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("clip", "transcription", "21-1 transcript readback (segments, speakers, word timing)", "/v1/transcription"),
	},
	{
		ID:             "color.apply-cdl",
		Method:         "POST",
		Path:           "/v1/apply-cdl",
		Summary:        "SetCDL on a node: --slope 'r g b' --offset 'r g b' --power 'r g b' --saturation s",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("color", "apply-cdl", "SetCDL on a node: --slope 'r g b' --offset 'r g b' --power 'r g b' --saturation s", "/v1/apply-cdl"),
	},
	{
		ID:             "color.apply-drx",
		Method:         "POST",
		Path:           "/v1/apply-drx",
		Summary:        "ApplyGradeFromDRX (REPLACES the node graph); --mode none|source|start",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("color", "apply-drx", "ApplyGradeFromDRX (REPLACES the node graph); --mode none|source|start", "/v1/apply-drx"),
	},
	{
		ID:             "color.apply-lut",
		Method:         "POST",
		Path:           "/v1/apply-lut",
		Summary:        "Graph.SetLUT on a node of each item (LUT must be discovered: refresh-luts)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("color", "apply-lut", "Graph.SetLUT on a node of each item (LUT must be discovered: refresh-luts)", "/v1/apply-lut"),
	},
	{
		ID:             "color.copy-grade",
		Method:         "POST",
		Path:           "/v1/copy-grade",
		Summary:        "CopyGrades from --source item to items",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("color", "copy-grade", "CopyGrades from --source item to items", "/v1/copy-grade"),
	},
	{
		ID:             "color.export-lut",
		Method:         "POST",
		Path:           "/v1/export-lut",
		Summary:        "ExportLUT of an item's grade (--cube 17|33|65|vlut)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("color", "export-lut", "ExportLUT of an item's grade (--cube 17|33|65|vlut)", "/v1/export-lut"),
	},
	{
		ID:             "color.gallery",
		Method:         "GET",
		Path:           "/v1/gallery",
		Summary:        "gallery still and PowerGrade albums with still counts",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("color", "gallery", "gallery still and PowerGrade albums with still counts", "/v1/gallery"),
	},
	{
		ID:             "color.gallery-album",
		Method:         "POST",
		Path:           "/v1/gallery-album",
		Summary:        "create / create-powergrade / set-current / rename / import (--paths) / export (--path --prefix --format) / delete-stills",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("color", "gallery-album", "create / create-powergrade / set-current / rename / import (--paths) / export (--path --prefix --format) / delete-stills", "/v1/gallery-album"),
	},
	{
		ID:             "color.group",
		Method:         "POST",
		Path:           "/v1/color-group",
		Summary:        "create / delete / rename / assign / remove a color group",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("color", "group", "create / delete / rename / assign / remove a color group", "/v1/color-group"),
	},
	{
		ID:             "color.groups",
		Method:         "GET",
		Path:           "/v1/color-groups",
		Summary:        "color groups with their clips (current timeline) and node counts",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("color", "groups", "color groups with their clips (current timeline) and node counts", "/v1/color-groups"),
	},
	{
		ID:             "color.info",
		Method:         "GET",
		Path:           "/v1/color-info",
		Summary:        "grade versions, group and node graph (labels, LUT per node, tools) of an item -- no lift/gamma/gain readback exists",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "item", WireName: "item"}, {PublicName: "timeline", WireName: "timeline"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("color", "info", "grade versions, group and node graph (labels, LUT per node, tools) of an item -- no lift/gamma/gain readback exists", "/v1/color-info"),
	},
	{
		ID:             "color.refresh-luts",
		Method:         "POST",
		Path:           "/v1/refresh-luts",
		Summary:        "RefreshLUTList after copying a .cube into the LUT folder",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("color", "refresh-luts", "RefreshLUTList after copying a .cube into the LUT folder", "/v1/refresh-luts"),
	},
	{
		ID:             "color.set-node",
		Method:         "POST",
		Path:           "/v1/set-node",
		Summary:        "node enable/cache, ResetAllGrades, ResetAllNodeColors, ApplyArriCdlLut",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("color", "set-node", "node enable/cache, ResetAllGrades, ResetAllNodeColors, ApplyArriCdlLut", "/v1/set-node"),
	},
	{
		ID:             "color.timeline-graph",
		Method:         "GET",
		Path:           "/v1/timeline-graph",
		Summary:        "timeline-level node graph",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "timeline", WireName: "timeline"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("color", "timeline-graph", "timeline-level node graph", "/v1/timeline-graph"),
	},
	{
		ID:             "color.version",
		Method:         "POST",
		Path:           "/v1/color-version",
		Summary:        "add / delete / load / rename a grade version (local or remote)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("color", "version", "add / delete / load / rename a grade version (local or remote)", "/v1/color-version"),
	},
	{
		ID:             "fusion.keyframes",
		Method:         "POST",
		Path:           "/v1/fusion-keyframes",
		Summary:        "BezierSpline keyframes on one input (--keys {frame: value}) or --clear",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("fusion", "keyframes", "BezierSpline keyframes on one input (--keys {frame: value}) or --clear", "/v1/fusion-keyframes"),
	},
	{
		ID:             "fusion.set",
		Method:         "POST",
		Path:           "/v1/fusion-set",
		Summary:        "SetInput values on a tool (Lock/StartUndo wrapped) with readback",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("fusion", "set", "SetInput values on a tool (Lock/StartUndo wrapped) with readback", "/v1/fusion-set"),
	},
	{
		ID:             "fusion.set-title",
		Method:         "POST",
		Path:           "/v1/set-title",
		Summary:        "Text+ shortcut: --text --font --style --size --color r,g,b --center x,y --outline w",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("fusion", "set-title", "Text+ shortcut: --text --font --style --size --color r,g,b --center x,y --outline w", "/v1/set-title"),
	},
	{
		ID:             "fusion.tool",
		Method:         "POST",
		Path:           "/v1/fusion-tool",
		Summary:        "add / delete / bypass / unbypass a tool in the comp",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("fusion", "tool", "add / delete / bypass / unbypass a tool in the comp", "/v1/fusion-tool"),
	},
	{
		ID:             "fusion.tools",
		Method:         "GET",
		Path:           "/v1/fusion-tools",
		Summary:        "tools in an item's Fusion comp (+ input values with --inputs / --all-inputs)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "item", WireName: "item"}, {PublicName: "comp", WireName: "comp"}, {PublicName: "regid", WireName: "regid"}, {PublicName: "read-inputs", WireName: "read-inputs"}, {PublicName: "all-inputs", WireName: "all-inputs"}, {PublicName: "timeline", WireName: "timeline"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("fusion", "tools", "tools in an item's Fusion comp (+ input values with --inputs / --all-inputs)", "/v1/fusion-tools"),
	},
	{
		ID:             "item.add-transition",
		Method:         "POST",
		Path:           "/v1/add-transition",
		Summary:        "21-1 AddTransition on an item edge (consumes media handles: 'right' needs the outgoing clip's tail handle",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("item", "add-transition", "21-1 AddTransition on an item edge (consumes media handles: 'right' needs the outgoing clip's tail handle", "/v1/add-transition"),
	},
	{
		ID:             "item.delete",
		Method:         "POST",
		Path:           "/v1/delete-items",
		Summary:        "DeleteClips on items (--ripple closes the gap)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("item", "delete", "DeleteClips on items (--ripple closes the gap)", "/v1/delete-items"),
	},
	{
		ID:             "item.fusion-comp",
		Method:         "POST",
		Path:           "/v1/item-fusion",
		Summary:        "Fusion comps on an item: add / import / export / delete / load / rename",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("item", "fusion-comp", "Fusion comps on an item: add / import / export / delete / load / rename", "/v1/item-fusion"),
	},
	{
		ID:             "item.fusion-comps",
		Method:         "GET",
		Path:           "/v1/fusion-comps",
		Summary:        "Fusion comps on an item (count + names)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "item", WireName: "item"}, {PublicName: "timeline", WireName: "timeline"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("item", "fusion-comps", "Fusion comps on an item (count + names)", "/v1/fusion-comps"),
	},
	{
		ID:             "item.info",
		Method:         "GET",
		Path:           "/v1/item-info",
		Summary:        "one item: properties, speed, fades, blanking, markers, comps, version, caches",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "item", WireName: "item"}, {PublicName: "timeline", WireName: "timeline"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("item", "info", "one item: properties, speed, fades, blanking, markers, comps, version, caches", "/v1/item-info"),
	},
	{
		ID:             "item.link",
		Method:         "POST",
		Path:           "/v1/link-items",
		Summary:        "SetClipsLinked (or --unlink)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("item", "link", "SetClipsLinked (or --unlink)", "/v1/link-items"),
	},
	{
		ID:             "item.list",
		Method:         "GET",
		Path:           "/v1/items",
		Summary:        "every timeline item with ref (V1:3), type, geometry, source range, clip",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "type", WireName: "type"}, {PublicName: "timeline", WireName: "timeline"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("item", "list", "every timeline item with ref (V1:3), type, geometry, source range, clip", "/v1/items"),
	},
	{
		ID:             "item.multicam",
		Method:         "POST",
		Path:           "/v1/multicam",
		Summary:        "21-1 multicam: create (from clips) / flatten / smart-switch (on an item)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("item", "multicam", "21-1 multicam: create (from clips) / flatten / smart-switch (on an item)", "/v1/multicam"),
	},
	{
		ID:             "item.set",
		Method:         "POST",
		Path:           "/v1/set-item",
		Summary:        "per-item edits: name, enabled, color, flags, speed (21-1), fades (21-1), blanking, caches, audio mapping",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("item", "set", "per-item edits: name, enabled, color, flags, speed (21-1), fades (21-1), blanking, caches, audio mapping", "/v1/set-item"),
	},
	{
		ID:             "item.set-properties",
		Method:         "POST",
		Path:           "/v1/set-item-properties",
		Summary:        "TimelineItemProperties (Pan/Tilt/Zoom/Crop/Opacity/CompositeMode/audio) -- STATIC values, no keyframes",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("item", "set-properties", "TimelineItemProperties (Pan/Tilt/Zoom/Crop/Opacity/CompositeMode/audio) -- STATIC values, no keyframes", "/v1/set-item-properties"),
	},
	{
		ID:             "pool.bin",
		Method:         "POST",
		Path:           "/v1/bin",
		Summary:        "create (idempotent) / delete / set-current / move / refresh a bin",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("pool", "bin", "create (idempotent) / delete / set-current / move / refresh a bin", "/v1/bin"),
	},
	{
		ID:             "pool.bins",
		Method:         "GET",
		Path:           "/v1/bins",
		Summary:        "media pool bin tree with clip counts",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "bin", WireName: "bin"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("pool", "bins", "media pool bin tree with clip counts", "/v1/bins"),
	},
	{
		ID:             "pool.clips",
		Method:         "GET",
		Path:           "/v1/pool",
		Summary:        "media pool clips",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "recursive", WireName: "recursive"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("pool", "clips", "media pool clips", "/v1/pool"),
	},
	{
		ID:             "pool.delete-clips",
		Method:         "POST",
		Path:           "/v1/delete-clips",
		Summary:        "delete media pool clips (--all-matches: every duplicate of a name/path)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("pool", "delete-clips", "delete media pool clips (--all-matches: every duplicate of a name/path)", "/v1/delete-clips"),
	},
	{
		ID:             "pool.import",
		Method:         "POST",
		Path:           "/v1/import-media",
		Summary:        "import media into a bin, skipping paths already in the pool (idempotent)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("pool", "import", "import media into a bin, skipping paths already in the pool (idempotent)", "/v1/import-media"),
	},
	{
		ID:             "pool.import-paths",
		Method:         "POST",
		Path:           "/v1/import",
		Summary:        "ImportMedia into the current pool folder",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("pool", "import-paths", "ImportMedia into the current pool folder", "/v1/import"),
	},
	{
		ID:             "pool.move-clips",
		Method:         "POST",
		Path:           "/v1/move-clips",
		Summary:        "move media pool clips to a bin",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("pool", "move-clips", "move media pool clips to a bin", "/v1/move-clips"),
	},
	{
		ID:             "pool.relink-clips",
		Method:         "POST",
		Path:           "/v1/relink-clips",
		Summary:        "relink clips from a filesystem folder, or --unlink",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("pool", "relink-clips", "relink clips from a filesystem folder, or --unlink", "/v1/relink-clips"),
	},
	{
		ID:             "pool.select-clip",
		Method:         "POST",
		Path:           "/v1/select-clip",
		Summary:        "select a media pool clip (GUI selection)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("pool", "select-clip", "select a media pool clip (GUI selection)", "/v1/select-clip"),
	},
	{
		ID:             "pool.selection",
		Method:         "GET",
		Path:           "/v1/selection",
		Summary:        "the editor's current selection",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("pool", "selection", "the editor's current selection", "/v1/selection"),
	},
	{
		ID:             "pool.stereo-clip",
		Method:         "POST",
		Path:           "/v1/stereo-clip",
		Summary:        "create a stereo clip from left + right clips",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("pool", "stereo-clip", "create a stereo clip from left + right clips", "/v1/stereo-clip"),
	},
	{
		ID:             "pool.sync-audio",
		Method:         "POST",
		Path:           "/v1/sync-audio",
		Summary:        "AutoSyncAudio on video + audio clips (waveform or timecode)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("pool", "sync-audio", "AutoSyncAudio on video + audio clips (waveform or timecode)", "/v1/sync-audio"),
	},
	{
		ID:             "project.archive",
		Method:         "POST",
		Path:           "/v1/archive-project",
		Summary:        "REFUSED on purpose: ProjectManager.ArchiveProject crashed Resolve 21-1 from a script (measured 2026-09-09)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "archive", "REFUSED on purpose: ProjectManager.ArchiveProject crashed Resolve 21-1 from a script (measured 2026-09-09)", "/v1/archive-project"),
	},
	{
		ID:             "project.close",
		Method:         "POST",
		Path:           "/v1/close-project",
		Summary:        "close the current project (no save unless --save)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "close", "close the current project (no save unless --save)", "/v1/close-project"),
	},
	{
		ID:             "project.cloud",
		Method:         "POST",
		Path:           "/v1/cloud-project",
		Summary:        "Blackmagic Cloud project create/load/import/restore (unverified: no cloud library here)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "cloud", "Blackmagic Cloud project create/load/import/restore (unverified: no cloud library here)", "/v1/cloud-project"),
	},
	{
		ID:             "project.create",
		Method:         "POST",
		Path:           "/v1/create-project",
		Summary:        "create AND load a project",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "create", "create AND load a project", "/v1/create-project"),
	},
	{
		ID:             "project.database",
		Method:         "GET",
		Path:           "/v1/database",
		Summary:        "current project database and the list of databases",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "database", "current project database and the list of databases", "/v1/database"),
	},
	{
		ID:             "project.delete",
		Method:         "POST",
		Path:           "/v1/delete-project",
		Summary:        "delete a project that is not loaded",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "delete", "delete a project that is not loaded", "/v1/delete-project"),
	},
	{
		ID:             "project.export",
		Method:         "POST",
		Path:           "/v1/export-project",
		Summary:        "export a project to a .drp file",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "export", "export a project to a .drp file", "/v1/export-project"),
	},
	{
		ID:             "project.folder",
		Method:         "POST",
		Path:           "/v1/folder",
		Summary:        "project-manager folder navigation: create/delete/open/root/parent",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "folder", "project-manager folder navigation: create/delete/open/root/parent", "/v1/folder"),
	},
	{
		ID:             "project.folders",
		Method:         "GET",
		Path:           "/v1/folders",
		Summary:        "project-manager folder listing (folders + projects in the current folder)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "folders", "project-manager folder listing (folders + projects in the current folder)", "/v1/folders"),
	},
	{
		ID:             "project.import",
		Method:         "POST",
		Path:           "/v1/import-project",
		Summary:        "import a .drp project file",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "import", "import a .drp project file", "/v1/import-project"),
	},
	{
		ID:             "project.list",
		Method:         "GET",
		Path:           "/v1/projects",
		Summary:        "projects in the current database folder",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "attributes", WireName: "attributes"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "list", "projects in the current database folder", "/v1/projects"),
	},
	{
		ID:             "project.load",
		Method:         "POST",
		Path:           "/v1/load-project",
		Summary:        "load a project (the page-null escape hatch)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "load", "load a project (the page-null escape hatch)", "/v1/load-project"),
	},
	{
		ID:             "project.rename",
		Method:         "POST",
		Path:           "/v1/rename-project",
		Summary:        "rename the current project",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "rename", "rename the current project", "/v1/rename-project"),
	},
	{
		ID:             "project.restore",
		Method:         "POST",
		Path:           "/v1/restore-project",
		Summary:        "RestoreProject from a .dra archive",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "restore", "RestoreProject from a .dra archive", "/v1/restore-project"),
	},
	{
		ID:             "project.save",
		Method:         "POST",
		Path:           "/v1/save-project",
		Summary:        "SaveProject on the current project",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "save", "SaveProject on the current project", "/v1/save-project"),
	},
	{
		ID:             "project.set-database",
		Method:         "POST",
		Path:           "/v1/set-database",
		Summary:        "switch the project database (Disk or PostgreSQL); CLOSES the open project",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "set-database", "switch the project database (Disk or PostgreSQL); CLOSES the open project", "/v1/set-database"),
	},
	{
		ID:             "project.set-settings",
		Method:         "POST",
		Path:           "/v1/set-project-settings",
		Summary:        "set project settings from JSON; one key per call, per-key result, read back",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "set-settings", "set project settings from JSON; one key per call, per-key result, read back", "/v1/set-project-settings"),
	},
	{
		ID:             "project.settings",
		Method:         "GET",
		Path:           "/v1/project-settings",
		Summary:        "all 158 project settings, or one key",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "key", WireName: "key"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "settings", "all 158 project settings, or one key", "/v1/project-settings"),
	},
	{
		ID:             "project.settings-preset",
		Method:         "POST",
		Path:           "/v1/project-settings-preset",
		Summary:        "apply/save/update/delete/export/import a project-settings preset",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "settings-preset", "apply/save/update/delete/export/import a project-settings preset", "/v1/project-settings-preset"),
	},
	{
		ID:             "project.settings-presets",
		Method:         "GET",
		Path:           "/v1/project-settings-presets",
		Summary:        "project-settings presets (name, width, height)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("project", "settings-presets", "project-settings presets (name, width, height)", "/v1/project-settings-presets"),
	},
	{
		ID:             "render.add-job",
		Method:         "POST",
		Path:           "/v1/add-render-job",
		Summary:        "configure (--preset / --format+--codec / --settings / --out / --name) and AddRenderJob with retry",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render", "add-job", "configure (--preset / --format+--codec / --settings / --out / --name) and AddRenderJob with retry", "/v1/add-render-job"),
	},
	{
		ID:             "render.delete-job",
		Method:         "POST",
		Path:           "/v1/delete-render-job",
		Summary:        "DeleteRenderJob JOB or --all",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render", "delete-job", "DeleteRenderJob JOB or --all", "/v1/delete-render-job"),
	},
	{
		ID:             "render.formats",
		Method:         "GET",
		Path:           "/v1/render-formats",
		Summary:        "render formats, codecs (desc -> ID) for --format, audio formats/codecs (21-1), resolutions, current selection",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "format", WireName: "format"}, {PublicName: "codec", WireName: "codec"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render", "formats", "render formats, codecs (desc -> ID) for --format, audio formats/codecs (21-1), resolutions, current selection", "/v1/render-formats"),
	},
	{
		ID:             "render.job-status",
		Method:         "GET",
		Path:           "/v1/render-job-status",
		Summary:        "one job's status (error strings normalized to Failed)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "job", WireName: "job"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render", "job-status", "one job's status (error strings normalized to Failed)", "/v1/render-job-status"),
	},
	{
		ID:             "render.jobs",
		Method:         "GET",
		Path:           "/v1/render-jobs",
		Summary:        "render queue with normalized per-job status",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render", "jobs", "render queue with normalized per-job status", "/v1/render-jobs"),
	},
	{
		ID:             "render.preset",
		Method:         "POST",
		Path:           "/v1/render-preset",
		Summary:        "load / save / update / delete / export / import / quick-export-on / quick-export-off a render preset",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render", "preset", "load / save / update / delete / export / import / quick-export-on / quick-export-off a render preset", "/v1/render-preset"),
	},
	{
		ID:             "render.presets",
		Method:         "GET",
		Path:           "/v1/render-presets",
		Summary:        "render preset names",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render", "presets", "render preset names", "/v1/render-presets"),
	},
	{
		ID:             "render.queue",
		Method:         "GET",
		Path:           "/v1/render-status",
		Summary:        "the render queue",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render", "queue", "the render queue", "/v1/render-status"),
	},
	{
		ID:             "render.quick-export",
		Method:         "POST",
		Path:           "/v1/quick-export",
		Summary:        "RenderWithQuickExport of the current timeline (EnableUpload always off)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render", "quick-export", "RenderWithQuickExport of the current timeline (EnableUpload always off)", "/v1/quick-export"),
	},
	{
		ID:             "render.quick-export-presets",
		Method:         "GET",
		Path:           "/v1/quick-export-presets",
		Summary:        "Quick Export preset names",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render", "quick-export-presets", "Quick Export preset names", "/v1/quick-export-presets"),
	},
	{
		ID:             "render.render",
		Method:         "POST",
		Path:           "/v1/render",
		Summary:        "render the current timeline (mp4/H264) with every guard",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render", "render", "render the current timeline (mp4/H264) with every guard", "/v1/render"),
	},
	{
		ID:             "render.set-format",
		Method:         "POST",
		Path:           "/v1/set-render-format",
		Summary:        "SetCurrentRenderFormatAndCodec (extension + codec ID)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render", "set-format", "SetCurrentRenderFormatAndCodec (extension + codec ID)", "/v1/set-render-format"),
	},
	{
		ID:             "render.set-mode",
		Method:         "POST",
		Path:           "/v1/set-render-mode",
		Summary:        "render mode: single (one file) or individual (per clip)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render", "set-mode", "render mode: single (one file) or individual (per clip)", "/v1/set-render-mode"),
	},
	{
		ID:             "render.set-settings",
		Method:         "POST",
		Path:           "/v1/set-render-settings",
		Summary:        "SetRenderSettings one key per call with per-key result (no readback exists; verify by file)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render", "set-settings", "SetRenderSettings one key per call with per-key result (no readback exists; verify by file)", "/v1/set-render-settings"),
	},
	{
		ID:             "render.smoke",
		Method:         "POST",
		Path:           "/v1/smoke",
		Summary:        "disposable-project end-to-end render proof",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render", "smoke", "disposable-project end-to-end render proof", "/v1/smoke"),
	},
	{
		ID:             "render.start",
		Method:         "POST",
		Path:           "/v1/start-render",
		Summary:        "StartRendering jobs (or all); --wait polls to completion",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render", "start", "StartRendering jobs (or all); --wait polls to completion", "/v1/start-render"),
	},
	{
		ID:             "render.stop",
		Method:         "POST",
		Path:           "/v1/stop-render",
		Summary:        "StopRendering",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render", "stop", "StopRendering", "/v1/stop-render"),
	},
	{
		ID:             "render.verify",
		Method:         "GET",
		Path:           "/v1/verify-render",
		Summary:        "ffprobe an output file (codec/size/fps/duration/audio) and check expectations -- the only render readback",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "path", WireName: "path"}, {PublicName: "codec", WireName: "codec"}, {PublicName: "width", WireName: "width"}, {PublicName: "height", WireName: "height"}, {PublicName: "fps", WireName: "fps"}, {PublicName: "audio", WireName: "audio"}, {PublicName: "min-duration", WireName: "min-duration"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("render", "verify", "ffprobe an output file (codec/size/fps/duration/audio) and check expectations -- the only render readback", "/v1/verify-render"),
	},
	{
		ID:             "storage.browse",
		Method:         "GET",
		Path:           "/v1/storage-browse",
		Summary:        "media storage folders (and files with --files) under a path",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "path", WireName: "path"}, {PublicName: "files", WireName: "files"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("storage", "browse", "media storage folders (and files with --files) under a path", "/v1/storage-browse"),
	},
	{
		ID:             "storage.clone-media",
		Method:         "POST",
		Path:           "/v1/clone-media",
		Summary:        "start (or --stop) a verified media clone (21-1 clone tool)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("storage", "clone-media", "start (or --stop) a verified media clone (21-1 clone tool)", "/v1/clone-media"),
	},
	{
		ID:             "storage.clone-status",
		Method:         "GET",
		Path:           "/v1/clone-status",
		Summary:        "media clone job status (21-1)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("storage", "clone-status", "media clone job status (21-1)", "/v1/clone-status"),
	},
	{
		ID:             "storage.import",
		Method:         "POST",
		Path:           "/v1/storage-import",
		Summary:        "import storage paths into the current pool folder (subclip range, clip mattes, timeline mattes)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("storage", "import", "import storage paths into the current pool folder (subclip range, clip mattes, timeline mattes)", "/v1/storage-import"),
	},
	{
		ID:             "storage.volumes",
		Method:         "GET",
		Path:           "/v1/storage-volumes",
		Summary:        "media storage mounted volumes",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("storage", "volumes", "media storage mounted volumes", "/v1/storage-volumes"),
	},
	{
		ID:             "system.apply",
		Method:         "POST",
		Path:           "/v1/preset",
		Summary:        "system presets: KIND layout|burnin|prefs|keyboard|fairlight, ACTION load|save|update|delete|export|import",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("system", "apply", "system presets: KIND layout|burnin|prefs|keyboard|fairlight, ACTION load|save|update|delete|export|import", "/v1/preset"),
	},
	{
		ID:             "system.disable-background-tasks",
		Method:         "POST",
		Path:           "/v1/disable-background-tasks",
		Summary:        "DisableBackgroundTasksForCurrentResolveSession (no re-enable; restart Resolve to restore auto-backup)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("system", "disable-background-tasks", "DisableBackgroundTasksForCurrentResolveSession (no re-enable; restart Resolve to restore auto-backup)", "/v1/disable-background-tasks"),
	},
	{
		ID:             "system.encrypt-dctl",
		Method:         "POST",
		Path:           "/v1/encrypt-dctl",
		Summary:        "21-1 EncryptDCTL a file (--name, --expiry ISO 8601, --out folder)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("system", "encrypt-dctl", "21-1 EncryptDCTL a file (--name, --expiry ISO 8601, --out folder)", "/v1/encrypt-dctl"),
	},
	{
		ID:             "system.export-frame",
		Method:         "POST",
		Path:           "/v1/export-frame",
		Summary:        "ExportCurrentFrameAsStill (.jpg/.png/.tif/.dpx/.drx; page-dependent)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("system", "export-frame", "ExportCurrentFrameAsStill (.jpg/.png/.tif/.dpx/.drx; page-dependent)", "/v1/export-frame"),
	},
	{
		ID:             "system.keyframe-mode",
		Method:         "GET",
		Path:           "/v1/keyframe-mode",
		Summary:        "read the keyframe mode (all|color|sizing)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("system", "keyframe-mode", "read the keyframe mode (all|color|sizing)", "/v1/keyframe-mode"),
	},
	{
		ID:             "system.list",
		Method:         "GET",
		Path:           "/v1/presets",
		Summary:        "layout / burn-in / prefs / keyboard (+current) / Fairlight preset lists",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("system", "list", "layout / burn-in / prefs / keyboard (+current) / Fairlight preset lists", "/v1/presets"),
	},
	{
		ID:             "system.page",
		Method:         "POST",
		Path:           "/v1/page",
		Summary:        "switch the GUI page",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("system", "page", "switch the GUI page", "/v1/page"),
	},
	{
		ID:             "system.quit",
		Method:         "POST",
		Path:           "/v1/quit",
		Summary:        "Resolve.Quit() (--save first)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("system", "quit", "Resolve.Quit() (--save first)", "/v1/quit"),
	},
	{
		ID:             "system.set-keyframe-mode",
		Method:         "POST",
		Path:           "/v1/set-keyframe-mode",
		Summary:        "set the keyframe mode",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("system", "set-keyframe-mode", "set the keyframe mode", "/v1/set-keyframe-mode"),
	},
	{
		ID:             "system.status",
		Method:         "GET",
		Path:           "/v1/status",
		Summary:        "product, version, Studio flag, page (null = writes will fail), project, timeline, database, keyboard preset, rendering",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("system", "status", "product, version, Studio flag, page (null = writes will fail), project, timeline, database, keyboard preset, rendering", "/v1/status"),
	},
	{
		ID:             "system.thumbnail",
		Method:         "GET",
		Path:           "/v1/thumbnail",
		Summary:        "GetCurrentClipThumbnailImage (Color page) -> --out FILE.ppm",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "out", WireName: "out"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("system", "thumbnail", "GetCurrentClipThumbnailImage (Color page) -> --out FILE.ppm", "/v1/thumbnail"),
	},
	{
		ID:             "system.validate-dctl",
		Method:         "GET",
		Path:           "/v1/validate-dctl",
		Summary:        "21-1 ValidateDCTL from --source text or --path file",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "source", WireName: "source"}, {PublicName: "path", WireName: "path"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("system", "validate-dctl", "21-1 ValidateDCTL from --source text or --path file", "/v1/validate-dctl"),
	},
	{
		ID:             "timeline.add-marker",
		Method:         "POST",
		Path:           "/v1/add-marker",
		Summary:        "add a timeline marker (or --item for a clip-relative item marker)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "add-marker", "add a timeline marker (or --item for a clip-relative item marker)", "/v1/add-marker"),
	},
	{
		ID:             "timeline.add-track",
		Method:         "POST",
		Path:           "/v1/add-track",
		Summary:        "AddTrack video/audio/subtitle (audio: --subtype mono|stereo|5.1|)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "add-track", "AddTrack video/audio/subtitle (audio: --subtype mono|stereo|5.1|)", "/v1/add-track"),
	},
	{
		ID:             "timeline.ai",
		Method:         "POST",
		Path:           "/v1/timeline-ai",
		Summary:        "subtitles / scene-cuts / stereo / dolby-vision / normalize (21-1) / auto-align (21-1)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "ai", "subtitles / scene-cuts / stereo / dolby-vision / normalize (21-1) / auto-align (21-1)", "/v1/timeline-ai"),
	},
	{
		ID:             "timeline.append",
		Method:         "POST",
		Path:           "/v1/append",
		Summary:        "AppendToTimeline with pre-resolved geometry + readback (current timeline only)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "append", "AppendToTimeline with pre-resolved geometry + readback (current timeline only)", "/v1/append"),
	},
	{
		ID:             "timeline.build",
		Method:         "POST",
		Path:           "/v1/build",
		Summary:        "edit-spec -> media pool + new timeline with readback",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "build", "edit-spec -> media pool + new timeline with readback", "/v1/build"),
	},
	{
		ID:             "timeline.clips",
		Method:         "GET",
		Path:           "/v1/clips",
		Summary:        "items per track of a timeline",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "audio", WireName: "audio"}, {PublicName: "timeline", WireName: "timeline"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "clips", "items per track of a timeline", "/v1/clips"),
	},
	{
		ID:             "timeline.compound-clip",
		Method:         "POST",
		Path:           "/v1/compound-clip",
		Summary:        "CreateCompoundClip from items",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "compound-clip", "CreateCompoundClip from items", "/v1/compound-clip"),
	},
	{
		ID:             "timeline.create",
		Method:         "POST",
		Path:           "/v1/create-timeline",
		Summary:        "CreateEmptyTimeline in the current project",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "create", "CreateEmptyTimeline in the current project", "/v1/create-timeline"),
	},
	{
		ID:             "timeline.create-from-clips",
		Method:         "POST",
		Path:           "/v1/create-timeline-from-clips",
		Summary:        "CreateTimelineFromClips: whole clips (positional refs) or --items JSON [{clip,startFrame,endFrame,recordFrame}]",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "create-from-clips", "CreateTimelineFromClips: whole clips (positional refs) or --items JSON [{clip,startFrame,endFrame,recordFrame}]", "/v1/create-timeline-from-clips"),
	},
	{
		ID:             "timeline.delete",
		Method:         "POST",
		Path:           "/v1/delete-timeline",
		Summary:        "delete a timeline by name",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "delete", "delete a timeline by name", "/v1/delete-timeline"),
	},
	{
		ID:             "timeline.delete-marker",
		Method:         "POST",
		Path:           "/v1/delete-marker",
		Summary:        "delete timeline/item markers by --frame, --custom-data or --color/All",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "delete-marker", "delete timeline/item markers by --frame, --custom-data or --color/All", "/v1/delete-marker"),
	},
	{
		ID:             "timeline.delete-track",
		Method:         "POST",
		Path:           "/v1/delete-track",
		Summary:        "DeleteTrack",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "delete-track", "DeleteTrack", "/v1/delete-track"),
	},
	{
		ID:             "timeline.duplicate",
		Method:         "POST",
		Path:           "/v1/duplicate-timeline",
		Summary:        "duplicate a timeline under a new name",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "duplicate", "duplicate a timeline under a new name", "/v1/duplicate-timeline"),
	},
	{
		ID:             "timeline.export",
		Method:         "POST",
		Path:           "/v1/export-timeline",
		Summary:        "Timeline.Export to AAF/DRT/EDL/FCPXML/OTIO/CSV/ALE/",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "export", "Timeline.Export to AAF/DRT/EDL/FCPXML/OTIO/CSV/ALE/", "/v1/export-timeline"),
	},
	{
		ID:             "timeline.export-spec",
		Method:         "GET",
		Path:           "/v1/export-spec",
		Summary:        "serialize a timeline to edit-spec JSON",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "timeline", WireName: "timeline"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "export-spec", "serialize a timeline to edit-spec JSON", "/v1/export-spec"),
	},
	{
		ID:             "timeline.fusion-clip",
		Method:         "POST",
		Path:           "/v1/fusion-clip",
		Summary:        "CreateFusionClip from items",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "fusion-clip", "CreateFusionClip from items", "/v1/fusion-clip"),
	},
	{
		ID:             "timeline.grab-still",
		Method:         "POST",
		Path:           "/v1/grab-still",
		Summary:        "GrabStill at the playhead, or --all first|middle for every clip",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "grab-still", "GrabStill at the playhead, or --all first|middle for every clip", "/v1/grab-still"),
	},
	{
		ID:             "timeline.import",
		Method:         "POST",
		Path:           "/v1/import-timeline",
		Summary:        "ImportTimelineFromFile (new timeline) or --into (AAF into the current timeline)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "import", "ImportTimelineFromFile (new timeline) or --into (AAF into the current timeline)", "/v1/import-timeline"),
	},
	{
		ID:             "timeline.info",
		Method:         "GET",
		Path:           "/v1/timeline-info",
		Summary:        "timeline geometry, rate, resolution, track counts, marks, blanking",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "timeline", WireName: "timeline"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "info", "timeline geometry, rate, resolution, track counts, marks, blanking", "/v1/timeline-info"),
	},
	{
		ID:             "timeline.insert-generator",
		Method:         "POST",
		Path:           "/v1/insert-generator",
		Summary:        "insert a generator / fusion-generator / ofx-generator / title / fusion-title / fusion-composition at the playhead",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "insert-generator", "insert a generator / fusion-generator / ofx-generator / title / fusion-title / fusion-composition at the playhead", "/v1/insert-generator"),
	},
	{
		ID:             "timeline.list",
		Method:         "GET",
		Path:           "/v1/timelines",
		Summary:        "timelines in the open project",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "list", "timelines in the open project", "/v1/timelines"),
	},
	{
		ID:             "timeline.mark",
		Method:         "POST",
		Path:           "/v1/timeline-mark",
		Summary:        "set (--mark-in/--mark-out) or --clear timeline mark in/out",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "mark", "set (--mark-in/--mark-out) or --clear timeline mark in/out", "/v1/timeline-mark"),
	},
	{
		ID:             "timeline.markers",
		Method:         "GET",
		Path:           "/v1/timeline-markers",
		Summary:        "timeline markers (frames relative to start)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "timeline", WireName: "timeline"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "markers", "timeline markers (frames relative to start)", "/v1/timeline-markers"),
	},
	{
		ID:             "timeline.normalize-modes",
		Method:         "GET",
		Path:           "/v1/normalize-modes",
		Summary:        "21-1 GetNormalizeAudioModes",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "timeline", WireName: "timeline"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "normalize-modes", "21-1 GetNormalizeAudioModes", "/v1/normalize-modes"),
	},
	{
		ID:             "timeline.rename",
		Method:         "POST",
		Path:           "/v1/rename-timeline",
		Summary:        "rename a timeline",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "rename", "rename a timeline", "/v1/rename-timeline"),
	},
	{
		ID:             "timeline.set-blanking",
		Method:         "POST",
		Path:           "/v1/set-blanking",
		Summary:        "21-1 timeline output blanking (pixels)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "set-blanking", "21-1 timeline output blanking (pixels)", "/v1/set-blanking"),
	},
	{
		ID:             "timeline.set-settings",
		Method:         "POST",
		Path:           "/v1/set-timeline-settings",
		Summary:        "set timeline settings from JSON; useCustomSettings applied first; frame rate is fixed at creation",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "set-settings", "set timeline settings from JSON; useCustomSettings applied first; frame rate is fixed at creation", "/v1/set-timeline-settings"),
	},
	{
		ID:             "timeline.set-timecode",
		Method:         "POST",
		Path:           "/v1/set-timecode",
		Summary:        "move the playhead (--playhead TC) / set start TC (--start TC)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "set-timecode", "move the playhead (--playhead TC) / set start TC (--start TC)", "/v1/set-timecode"),
	},
	{
		ID:             "timeline.set-track",
		Method:         "POST",
		Path:           "/v1/set-track",
		Summary:        "rename / enable / lock / voice-isolate a track",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "set-track", "rename / enable / lock / voice-isolate a track", "/v1/set-track"),
	},
	{
		ID:             "timeline.settings",
		Method:         "GET",
		Path:           "/v1/timeline-settings",
		Summary:        "timeline settings (project settings unless useCustomSettings=1)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "key", WireName: "key"}, {PublicName: "timeline", WireName: "timeline"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "settings", "timeline settings (project settings unless useCustomSettings=1)", "/v1/timeline-settings"),
	},
	{
		ID:             "timeline.switch",
		Method:         "POST",
		Path:           "/v1/switch-timeline",
		Summary:        "make a timeline current (switches the GUI)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "switch", "make a timeline current (switches the GUI)", "/v1/switch-timeline"),
	},
	{
		ID:             "timeline.timecode",
		Method:         "GET",
		Path:           "/v1/timecode",
		Summary:        "playhead + start timecode + frame range",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "timeline", WireName: "timeline"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "timecode", "playhead + start timecode + frame range", "/v1/timecode"),
	},
	{
		ID:             "timeline.tracks",
		Method:         "GET",
		Path:           "/v1/tracks",
		Summary:        "tracks with name, enabled, locked, subtype, item count, voice isolation",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "timeline", WireName: "timeline"}},
		HeaderParams:   []codeOrchParamBinding{},
		Mutating:       false,
		keywords:       codeOrchKeywords("timeline", "tracks", "tracks with name, enabled, locked, subtype, item count, voice isolation", "/v1/tracks"),
	},
}

// codeOrchStopwords filters two-letter and short common-word substrings
// that pollute ranking via the substring-contains rule. Without them, a
// search for "list links" matches every endpoint whose description
// contains "is enrolled" because "is" is two chars and the matcher
// accepts kw.contains(t) || t.contains(kw).
var codeOrchStopwords = map[string]bool{
	"a": true, "an": true, "and": true, "are": true, "as": true,
	"at": true, "be": true, "by": true, "for": true, "from": true,
	"has": true, "in": true, "is": true, "it": true, "its": true,
	"of": true, "on": true, "or": true, "that": true, "the": true,
	"this": true, "to": true, "was": true, "will": true, "with": true,
	"your": true, "you": true, "any": true, "all": true,
}

// codeOrchKeywords produces the lowercase token stream used for search
// ranking. Defined at package level so the registry initializer can call it
// inline above without pulling in a separate precompute step.
func codeOrchKeywords(resource, endpoint, summary, path string) []string {
	raw := strings.ToLower(resource + " " + endpoint + " " + summary + " " + path)
	raw = strings.Map(func(r rune) rune {
		switch r {
		case '_', '-', '/', '{', '}', '.', ',', ':', ';':
			return ' '
		}
		return r
	}, raw)
	out := make([]string, 0, 16)
	seen := map[string]bool{}
	for _, tok := range strings.Fields(raw) {
		if len(tok) < 3 || codeOrchStopwords[tok] || seen[tok] {
			continue
		}
		seen[tok] = true
		out = append(out, tok)
	}
	return out
}

func codeOrchEndpointMetadata(ep *codeOrchEndpoint) map[string]any {
	out := map[string]any{
		"endpoint_id": ep.ID,
		"method":      ep.Method,
		"path":        ep.Path,
		"summary":     ep.Summary,
	}
	return out
}

func findCodeOrchEndpoint(id string) *codeOrchEndpoint {
	for i := range codeOrchEndpoints {
		if codeOrchEndpoints[i].ID == id {
			return &codeOrchEndpoints[i]
		}
	}
	return nil
}

const (
	codeOrchSearchDefaultLimit = 10
	codeOrchSearchMaxLimit     = 100
)

func codeOrchSearchLimit(args map[string]any) int {
	if v, ok := args["limit"].(float64); ok && v > 0 {
		if v > float64(codeOrchSearchMaxLimit) {
			return codeOrchSearchMaxLimit
		}
		return int(v)
	}
	return codeOrchSearchDefaultLimit
}

func handleCodeOrchSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || strings.TrimSpace(query) == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}
	limit := codeOrchSearchLimit(args)

	terms := codeOrchKeywords("", "", query, "")
	type scored struct {
		ep    *codeOrchEndpoint
		score int
	}
	results := make([]scored, 0, len(codeOrchEndpoints))
	for i := range codeOrchEndpoints {
		ep := &codeOrchEndpoints[i]
		score := 0
		for _, t := range terms {
			for _, kw := range ep.keywords {
				if kw == t {
					score += 2
				} else if strings.Contains(kw, t) || strings.Contains(t, kw) {
					score++
				}
			}
		}
		if score > 0 {
			results = append(results, scored{ep: ep, score: score})
		}
	}
	sort.SliceStable(results, func(i, j int) bool { return results[i].score > results[j].score })
	if len(results) > limit {
		results = results[:limit]
	}

	out := make([]map[string]any, 0, len(results))
	for _, r := range results {
		item := codeOrchEndpointMetadata(r.ep)
		item["score"] = r.score
		out = append(out, item)
	}
	text, err := bound.JSON(map[string]any{"count": len(out), "results": out})
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding search results: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}

func handleCodeOrchGet(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call davinci-resolve_search first)"), nil
	}
	ep := findCodeOrchEndpoint(id)
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call davinci-resolve_search to discover valid ids", id)), nil
	}
	if ep.Method != "GET" {
		return mcplib.NewToolResultError(fmt.Sprintf("endpoint_id %q is %s, but davinci-resolve_get only permits GET endpoints", id, ep.Method)), nil
	}
	text, err := bound.JSON(codeOrchEndpointMetadata(ep))
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding endpoint metadata: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}

func handleCodeOrchExecute(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call davinci-resolve_search first)"), nil
	}

	ep := findCodeOrchEndpoint(id)
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call davinci-resolve_search to discover valid ids", id)), nil
	}

	params, _ := args["params"].(map[string]any)
	if params == nil {
		params = map[string]any{}
	}

	c, platformSession, err := newMCPClient(ctx)
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	if platformSession != nil {
		defer platformSession.ZeroCredentials()
	}
	if err := cli.AdoptMCPOutputSemantics(platformSession, params); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path := ep.Path
	for _, p := range ep.Positional {
		if v, ok := params[p]; ok && strings.Contains(path, "{"+p+"}") {
			path = strings.ReplaceAll(path, "{"+p+"}", mcpPathValue(v))
			delete(params, p)
		}
	}

	hdrs := make(map[string]string, len(ep.HeaderOverrides)+len(ep.HeaderParams))
	for k, v := range ep.HeaderOverrides {
		hdrs[k] = v
	}
	for _, binding := range ep.HeaderParams {
		if binding.Default != "" {
			hdrs[binding.WireName] = binding.Default
		}
		for _, key := range []string{binding.PublicName, binding.WireName} {
			if v, ok := params[key]; ok {
				hdrs[binding.WireName] = formatMCPParamValue(v)
				delete(params, key)
				break
			}
		}
	}
	if len(hdrs) == 0 {
		hdrs = nil
	}

	// Route params to their runtime slots. GET/DELETE params are query
	// strings; write methods split spec-declared query params from the
	// remaining params used as the request body below.
	query := map[string]string{}
	if ep.Method == "GET" || ep.Method == "DELETE" {
		for k, v := range params {
			query[codeOrchWireQueryName(ep.QueryParams, k)] = formatMCPParamValue(v)
		}
	} else {
		// Route spec-declared in:query params to the query string for write
		// methods too. Without this, a query param (e.g. sendToLedger on
		// PUT /ledger/voucher/{id}) wrongly lands in the JSON body and the
		// API silently ignores it or rejects the request. The remaining
		// params stay in the map for codeOrchWriteBody (the JSON body).
		if enc := codeOrchSplitQuery(ep.QueryParams, params); enc != "" {
			sep := "?"
			if strings.Contains(path, "?") {
				sep = "&"
			}
			path += sep + enc
		}
	}

	writeBody := func() any {
		if ep.BodyIsArray {
			return codeOrchArrayBody(params)
		}
		return codeOrchWriteBody(params)
	}
	var data json.RawMessage
	switch ep.Method {
	case "GET":
		if len(hdrs) > 0 {
			if ep.Mutating {
				data, err = c.GetMutatingWithHeaders(ctx, path, query, hdrs)
			} else {
				data, err = c.GetWithHeaders(ctx, path, query, hdrs)
			}
		} else {
			if ep.Mutating {
				data, err = c.GetMutating(ctx, path, query)
			} else {
				data, err = c.Get(ctx, path, query)
			}
		}
	case "DELETE":
		if len(hdrs) > 0 {
			data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, query, hdrs)
		} else {
			data, _, err = c.DeleteWithParams(ctx, path, query)
		}
	case "POST":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PostWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Post(ctx, path, body)
		}
	case "PUT":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PutWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Put(ctx, path, body)
		}
	case "PATCH":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PatchWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Patch(ctx, path, body)
		}
	default:
		return mcplib.NewToolResultError(fmt.Sprintf("unsupported method %q", ep.Method)), nil
	}
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	text := bound.EndpointResponse(ep.Method, data)
	if platformSession != nil {
		text = bound.WithMetadata(text, platformSession.OutputMetadata())
	}
	return mcplib.NewToolResultText(text), nil
}

// codeOrchWriteBody returns the value handed to the client layer as the
// request body for write methods (POST/PUT/PATCH). It MUST be the structured
// params map, never pre-marshaled bytes.
//
// client.do() marshals the body value exactly once. Handing it []byte makes
// json.Marshal([]byte) emit a base64-encoded JSON *string*, so the API
// receives "eyJ...==" where it expects the request object. Strict JSON APIs
// reject that as the wrong type at the body root. GET/DELETE carry no body,
// so this defect stays latent until the first write attempt.
func codeOrchWriteBody(params map[string]any) any {
	return params
}

// codeOrchArrayBody returns the request body for endpoints whose schema root
// is a bare top-level JSON array (ep.BodyIsArray). Such a body cannot be
// expressed as the params object, so the agent supplies the array under the
// conventional params key "body" (these endpoints have no flattened named
// params, so there is no collision risk). When present and array-shaped it is
// sent as the top-level array the API expects. Otherwise params is returned
// unchanged so a malformed call fails loudly at the API (HTTP 422) instead of
// silently sending the wrong shape or a partial write — financial mutations
// are never retried with body-variant guesses (broken-convenience guardrail).
func codeOrchArrayBody(params map[string]any) any {
	if v, ok := params["body"]; ok {
		if arr, ok := v.([]any); ok {
			return arr
		}
	}
	return params
}

// codeOrchSplitQuery removes spec-declared in:query params from params and
// returns them URL-encoded for appending to the request path. The remaining
// entries stay in the map for codeOrchWriteBody (the JSON body), so a write
// method's query parameters never get buried in the body. Mutates params by
// design (deletes the consumed query keys).
func codeOrchSplitQuery(queryParams []codeOrchParamBinding, params map[string]any) string {
	uv := neturl.Values{}
	for _, q := range queryParams {
		for _, key := range []string{q.PublicName, q.WireName} {
			if key == "" {
				continue
			}
			if v, ok := params[key]; ok {
				uv.Set(q.WireName, formatMCPParamValue(v))
				delete(params, key)
				break
			}
		}
	}
	return uv.Encode()
}

func codeOrchWireQueryName(queryParams []codeOrchParamBinding, name string) string {
	for _, q := range queryParams {
		if q.PublicName == name || q.WireName == name {
			return q.WireName
		}
	}
	return name
}
